version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: senha123
      POSTGRES_DATABASE: ED_BURGUER
      POSTGRES_USER: ed
      POSTGRES_PASSWORD: senha123
