INSERT INTO tb_user (name, email, phone, password, role) VALUES ('Ed', 'ed@gmail.com', '81911112222', 'senha123', 'ADMIN');
INSERT INTO tb_user (name, email, phone, password, role) VALUES ('Frankem', 'frankem@gmail.com', '81911112222','senha123', 'USER');
INSERT INTO tb_user (name, email, phone, password, role) VALUES ('Gabriel', 'gabriel@gmail.com', '81911112222', 'senha123', 'USER');

INSERT INTO tb_district (name, delivery_price) VALUES ('Pau Amarelo', 3.0);
INSERT INTO tb_district (name, delivery_price) VALUES ('Beira Mar', 5.0);
INSERT INTO tb_district (name, delivery_price) VALUES ('Conceição', 4.0);

INSERT INTO tb_address (name, street, number, complement, district_id, user_id) VALUES ('Casa', 'Rua Arábia Saudita', '22A', null, 1, 1);
INSERT INTO tb_address (name, street, number, complement, district_id, user_id) VALUES ('Casa da Namorada', 'Rua Cavaleiro', '37', 'Teste', 2, 2);
INSERT INTO tb_address (name, street, number, complement, district_id, user_id) VALUES ('Casa', 'Rua Edson Nieling Lundgren', '10', 'Próximo da Panificadora Praia da Conceição', 3, 3);


INSERT INTO tb_product_category (name, image_url) VALUES ('Cachorro Quente', '02-08-2023-22-08-16hot-dog-svgrepo.svg');
INSERT INTO tb_product_category (name, image_url) VALUES ('Hambúrguer', '04-08-2023-17-22-21hamburguer-icon.svg');
INSERT INTO tb_product_category (name, image_url) VALUES ('Pizza', '30-11-2023-21-35-02pizza.svg');
INSERT INTO tb_product_category (name, image_url) VALUES ('Porções', '30-11-2023-21-35-15portion.svg');
INSERT INTO tb_product_category (name, image_url) VALUES ('Salgados', '30-11-2023-21-35-32salty.svg');
INSERT INTO tb_product_category (name, image_url) VALUES ('Açai', '04-08-2023-17-22-46acai-icon.svg');
INSERT INTO tb_product_category (name, image_url) VALUES ('Bebidas', '04-08-2023-17-23-02bebidas-icon.svg');

INSERT INTO tb_option (name, maximum_amount, required, product_category_id) VALUES ('Escolha uma Opção', 1, true, 1);
INSERT INTO tb_option (name, maximum_amount, required, product_category_id) VALUES ('Acréscimos', 5, false, 1);

INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Pão HotDog', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Salsicha', null, 2.50, 3);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Mussarela', null, 2.50, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Milho e Ervilha', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Vinagrete', null, 2.50, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Batata palha', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Purê de Batata', null, 3, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Maionese', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Catchup', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Mostarda', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Frango', 'Desfiado', 5.00, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Bacon', null, 6.00, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Catupiry', null, 4, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Ovo', 'Frito', 2.50, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Ovo de Codorna', null, 4, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Uva Passa', null, 2.50, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Cheddar', null, 4, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Pão de Hambúrguer', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Hambúrguer', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Presunto', null, 2.50, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Maionese Caseira', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Alface e Tomate', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('File de frango', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Sem Prensar', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Prensado', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Calabresa', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Massa de Pizza', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Molho de Tomate', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Orégano', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Marguerita', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('3 Queijos', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Batata Frita', null, null, 1);
INSERT INTO tb_ingredient (name, description, price, repetitions) VALUES ('Onion Rings', null, null, 1);

INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Cachorro Quente Piloto', '28-11-2023-17-51-01hotdog-piloto.jpg', 'Pão, Salsicha, Mussarela, Milho, Ervilha, Batata Palha, Vinagrete', 6.90, 1);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Cachorro Quente Caprichoso', '28-11-2023-17-51-30hotdog-caprichoso.jpg', 'Pão, purê, salsicha, maionese, catchup, mostarda, batata palha, vinagrete', 9.90, 1);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Cachorro Quente Cuidadoso', '28-11-2023-17-51-48hotdog-cuidadoso.jpg', 'Pão, Purê, Milho, Ervilha, Maionese, Salsicha, Batata Palha, Vinagrete', 12.90, 1);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Cachorro Quente Amoroso', '28-11-2023-17-51-59hotdog-amoroso.jpg', 'Pao, purê de batata, Salsicha, Vinagrete, Ervilha, Milho, Bacon, Cheddar, Maionese, Catchup, Mostarda e Batata palha', 15.90, 1);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Cachorro Quente Atencioso', '28-11-2023-17-52-04hotdog-atencioso.jpg', 'Pão, Salsicha, Purê, Vinagrete, Milho, Ervilha, Bacon, Catupiry, Maionese, Catchup, Mostarda e Batata palha', 19.90, 1);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Cachorro Quente Verdadeiro', '28-11-2023-17-52-15hotdog-verdadeiro.jpg', 'Pão, Salsicha, Purê de batata, Vinagrete, Milho, Ervilha, Frango desfiado, Bacon, Catupiry, Maionese, Ketchup, Mostarda e batata palha', 24.90, 1);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Hambúrguer Piloto', '29-11-2023-08-58-01hamburguer-piloto.jpg', 'Pão, hambúrguer, presunto, mussarela, maionese caseira, alface e tomate.', 8.90, 2);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Hambúrguer Caprichoso', '29-11-2023-08-58-47hamburguer-caprichoso.jpg', 'Pão, alface, tomate, hambúrguer, bacon, presunto, mussarela e maionese caseira.', 11.90, 2);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Hambúrguer Cuidadoso', '29-11-2023-08-59-04hamburguer-cuidadoso.jpg', 'Pão, alface, tomate, hambúrguer, calabresa, presunto, mussarela e maionese caseira.', 14.90, 2);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Hambúrguer Amoroso', '29-11-2023-08-59-39hamburguer-amoroso.jpg', 'Pão, alface, tomate, filé de frango, ovo, bacon, presunto, mussarela e maionese caseira.', 19.90, 2);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Hambúrguer Atencioso', '29-11-2023-09-00-08hamburguer-atencioso.jpg', 'Pão, alface, tomate, hambúrguer, ovo, bacon, presunto, mussarela e maionese caseira.', 22.90, 2);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Hambúrguer Verdadeiro', '29-11-2023-09-00-20hamburguer-verdadeiro.jpg', 'Pão, hambúrguer, alface, tomate, filé de frango, presunto, mussarela e maionese caseira.', 24.90, 2);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pizza de Calabresa', '30-11-2023-21-40-05pizza-pepperoni.jpg', '', 24.90, 3);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pizza de Presunto', '30-11-2023-21-40-11pizza-ham.jpeg', '', 24.90, 3);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pizza de Frango', '30-11-2023-21-40-13pizza-chicken.jpg', '', 24.90, 3);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pizza de Mussarela', '30-11-2023-21-40-21pizza-mozzarella.jpg', '', 24.90, 3);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pizza de Marguerita', '30-11-2023-21-41-31pizza-margherita.jpg', '', 24.90, 3);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pizza de 3 Queijos', '30-11-2023-21-41-45pizza-cheese.jpeg', '', 24.90, 3);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Bata Frita', '30-11-2023-22-49-05french-fries.jpeg', '', 9.90, 4);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Bata Frita com Bacon e Cheddar', '30-11-2023-22-49-05french-fries-with-cheddar.jpeg', '', 11.90, 4);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Onion Rings', '30-11-2023-22-51-03onion-rings.jpeg', '', 4.90, 4);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Coxinha de Frango', '01-12-2023-08-44-20chicken-drumstick.jpeg', '', 4.90, 5);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Coxinha de Frango com Catupry', '01-12-2023-08-44-26coxinha-chicken-catupiry.jpeg', '', 4.90, 5);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Pastel', '01-12-2023-08-44-33pastry.jpeg', '', 4.90, 5);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Enroladinho', '01-12-2023-08-45-01curled.jpeg', '', 4.90, 5);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Empada de Frango', '01-12-2023-08-45-29chicken-pie.jpeg', '', 4.90, 5);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Empada Doce', '01-12-2023-08-45-32sweet-pie.jpeg', '', 4.90, 5);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Açai Simples', '04-08-2023-17-27-52acai-simples.jpg', '', 6.90, 6);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Açai Amoroso', '04-08-2023-17-28-09acai-amoroso.jpg', '', 14.90, 6);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Açai Caprichoso', '04-08-2023-17-28-24acai-caprichoso.jpg', '', 22.90, 6);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Coca Cola (2 Litros)', '04-08-2023-17-30-03coca-cola-2L.jpeg', '', 14.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Coca Cola (350ml)', '04-08-2023-17-30-30coca-cola-350ml.jpeg', 'COCA COLA LATA', 5.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Coca Cola (600ml)', '04-08-2023-17-30-50coca-cola-600ml.jpeg', '', 7.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Fanta Laranja (2 Litros)', '04-08-2023-17-31-11fanta-laranja-2l.jpeg', '', 12.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Fanta Laranja (350ml)', '04-08-2023-17-31-29fanta-laranja-350ml.jpeg', '', 5.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Fanta Uva (350ml)', '04-08-2023-17-31-45fanta-uva-350ml.jpeg', '', 5.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Guaraná (350ml)', '04-08-2023-17-32-01guarana-350ml.jpeg', '', 5.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('H2O (500ml)', '04-08-2023-17-32-20h2o-500ml.jpeg', '', 5.90, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Água com Gás (500ml)', '04-08-2023-17-32-38agua-500ml.jpeg', '', 4.50, 7);
INSERT INTO tb_product (name, image_url, description, price, product_category_id) VALUES ('Água sem Gás (500ml)', '04-08-2023-17-32-38agua-500ml.jpeg', '', 3.50, 7);

INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (1, 1);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (1, 2);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (1, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (1, 4);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (1, 5);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (1, 6);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 1);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 7);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 8);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 9);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 10);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 6);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (2, 5);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 1);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 7);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 4);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 8);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 2);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 6);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (3, 5);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 1);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 7);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 2);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 5);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 4);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 16);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 8);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 9);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 10);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (4, 6);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 1);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 2);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 7);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 5);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 4);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 8);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 9);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 10);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (5, 6);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 1);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 2);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 7);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 5);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 4);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 11);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 13);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 8);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 9);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 10);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (6, 6);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 17);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 18);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 20);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 21);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (7, 22);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 17);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 21);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 22);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 18);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (8, 20);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 17);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 21);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 22);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 18);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 26);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (9, 20);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 17);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 18);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 21);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 22);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 11);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 14);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (10, 20);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 17);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 21);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 22);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 18);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 14);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (11, 20);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 17);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 18);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 21);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 22);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 11);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (12, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (13, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (13, 28);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (13, 29);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (13, 26);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (14, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (14, 28);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (14, 29);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (14, 19);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (15, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (15, 28);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (15, 29);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (15, 11);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (16, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (16, 28);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (16, 29);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (16, 3);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (17, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (17, 28);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (17, 29);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (17, 30);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (18, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (18, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (18, 27);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (18, 31);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (19, 32);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (20, 32);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (20, 12);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (20, 16);
INSERT INTO tb_products_ingredients (product_id, ingredient_id) VALUES (21, 33);

INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (1, 24);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (1, 25);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 14);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 12);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 13);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 17);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 11);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 4);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 3);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 15);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 7);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 2);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 16);
INSERT INTO tb_options_ingredients (option_id, ingredient_id) VALUES (2, 5);

INSERT INTO orders (user_id, address_id, status, payment, receive_type, cpf, price) VALUES (3, 3, 4, 1, 2, '00000000000', 26.90);
INSERT INTO orders (user_id, address_id, status, payment, receive_type, cpf, price) VALUES (3, 3, 1, 1, 2, '00000000000', 43.80);
INSERT INTO orders (user_id, address_id, status, payment, receive_type, cpf, price) VALUES (2, 2, 2, 2, 2, '00000000000', 27.90);
INSERT INTO orders (user_id, address_id, status, payment, receive_type, cpf, price) VALUES (1, 1, 3, 3, 1, '00000000000', 17.80);

INSERT INTO product_orders (product_id, observation, quantity) VALUES ( 3, 'isso é um teste', 1);
INSERT INTO product_orders (product_id, observation, quantity) VALUES (15, 'isso é um teste', 1);
INSERT INTO product_orders (product_id, observation, quantity) VALUES (31, 'isso é um teste', 1);
INSERT INTO product_orders (product_id, observation, quantity) VALUES (30, 'isso é um teste', 1);
INSERT INTO product_orders (product_id, observation, quantity) VALUES (19, 'isso é um teste', 1);
INSERT INTO product_orders (product_id, observation, quantity) VALUES (24, 'isso é um teste', 1);

INSERT INTO order_options (title, product_orders_id) VALUES ('Escolha uma Opção', 1);
INSERT INTO order_options (title, product_orders_id) VALUES ('Adicionais', 1);

INSERT INTO order_options_ingredients (order_option_id, ingredient_id) VALUES (1, 24);
INSERT INTO order_options_ingredients (order_option_id, ingredient_id) VALUES (2, 12);
INSERT INTO order_options_ingredients (order_option_id, ingredient_id) VALUES (2, 15);